const ATLAS: readonly string[] = [
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 0
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 1
  'P.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PPP.PPP..PP', // 2
  'P.....P.....PP.....P.....PP.....P.....PP#....P.....PP.....P.....PP.....P.....PP.....P.....PP.....P.....PP.....P.....PP.....P.....PP.....P.....PP', // 3
  '.................................P..PPPPPPPPP..........PPPPPP...................................................................................', // 4
  '.............................PPPPPPPPP..P...........PPPPPPPPPPP.................................................................................', // 5
  '.................................P...........PP.....PPPPPPPPPPPP................................................................................', // 6
  '............................PPPPPPPPPP..............PPPPPPPPPPPPP.................P...........PPPPPPPPPPPPPPP...................................', // 7
  '............#.........FFFFFFFFFFFFFFFFFFFFFFF......PPPPPPPPPPPPPPP..........#################################################...................', // 8
  '.......########FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.PPPPPPPPPPPPPP.....###FFFFFFFFFFFFFFFFFF^FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...........', // 9
  '....###########FFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFF.PPPPPPPPPPPPP...#####FFFFFFFFFFFFFFFFFF^FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.....', // 10
  '....###########FFFFFFFFFFFFFFFFFF.......FFFFFFFFFFF.PPPPPPPPPPPP..#######FFFFFFFFFFFFFFFFFF^FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF##...', // 11
  '.............##FFFFFF^FFFFFFFFFF.........FFFFFFFFFF#.PPPPPPPPPP...#######FFFFFFFFFFFFFFFFFF^FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF####.', // 12
  '................FFFFF^FFFFFFFFF...........FFFFFFFFF#...........PP.#######FFFFFFFFFFFFFFFFFF^FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF##^#.', // 13
  '.................#####^#########.........##########................######FFFFFFFFFFFFFFFFFF^FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF#####', // 14
  '..................##FF^FF########.......##########..................############FFFFFFFFFFF^FFFFF###############################^^^^^########^##', // 15
  '...................#FF^FF###########.############...................############FFFFFFFFFFF^FFFFF####################################^^########.', // 16
  '....................FF^^F#######################...................#############FFFFFFFFFFF^FFFFF###DDDDD^^^^^^^^DDDDDD#######################..', // 17
  '.....................FF^F###############..######...................#############FFFFFFFFFFF^FFFFF###DDDDDDDDDDDDDDDDDDD#####################....', // 18
  '.....................FF^F################^######...................#############^^^#########.#######DDDDDDDDDDDDDDDDDDD##############^###.......', // 19
  '......................F^F#################^FFFFF...................######^^^^^^######.#^^^^^.#######DDDDDDDDDDDDDDDDDDD##############^^#........', // 20
  '......................F^DDDDDDDDD#########^FFFFF...................####^^^#########.....###...######DDD^^^^DDDDDDDDDDDD###############^#........', // 21
  '.......................^^DDDDDDDD#########F^FFF...................###########....#.##.######.#######DDDDDD^^DDDDDDDDDDD##############.^#........', // 22
  '........................^DDDDDDDD#########F^FFF..................##^^^^^^DDDDDDDDD....D#####.#######DDDDDDDDDDDDDDDDDDD#############.^^#........', // 23
  '........................^^DDDDDDD#########F^FF..................DDDDDDDDDDDDDDDDDDDDDDDD#############^^^^^^^^^^####################..#..........', // 24
  '.........................^D^DDDDD####..#######.................DDDDDDDDDDDDDDDDDDDDDDDDDDD#DDDDDDDDD#^^^^^^^^^^###################..............', // 25
  '...........................D^DDDD###.....####..................DDDDDDDDDDDDDDDDDDDDDDDDDDDD^^^^DDDDD#^^^^^^^^^^##################...............', // 26
  '............................#^#####....######.................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD^^^DD^^^^^^^^^^^^##################...............', // 27
  '.............................#^####..........##...............DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD^^DDDDDD########################................', // 28
  '..............................####............................####DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD########################................', // 29
  '...............................#####.........................#########################DDDDDDDDD#####DDDD####FFFFFFFFFFFFFFFFFFFF................', // 30
  '.................................#####........................########################DDDDDDDDD#..##########FFFFFFFFFFFFFFFFFF..................', // 31
  '...................................#####.#######..............########################DDD^DDDDD#.....#######FFFFFFFFFFFFFFFFF...................', // 32
  '.....................................####^#########.............##########################^^####.....##^####FFFFFFFFFFFFFFFF...F................', // 33
  '........................................#^#############...........###########################.........#^^###FFFFFFFFFFFFFFF.....F...............', // 34
  '........................................^^##FFFFFFFFFFFF#...........###########################.......##^###FF..FFFFFFFFF.......F...............', // 35
  '........................................^##FFFFFFFFFFFFFF#...........###################^######.........^###F.....FFFFFFF........F..............', // 36
  '........................................^##FFFFFFFFFFFFFFF#..........#############F#####^######....................FFFFF.........F..............', // 37
  '........................................^##FFFFFFFFFFFFFFFF..........###FFFFFFFFFFFFF###^######.............F...FF........F.....................', // 38
  '........................................^##FFFFFFFFFFFFFFFF...........##FFFFFFFFFFFFFF##^#####...................FFFF..FFFFFFF..................', // 39
  '........................................^##FFFFFFFFFFFFFFF............#FFFFFFFFFFFFFFFFF^#####.....................FFF....F...FF................', // 40
  '........................................^###FFFFFFFFFFFFFF............#FFFFFFFFFFFFFFFFF^#####.......................FF........F.....F..........', // 41
  '........................................^####FFFFFFFFFFFF..............#FFFFFFFFFFFFFFFF^####.........................FFFFFFF.....FF^^FFFF......', // 42
  '........................................^#####FFFFFFFFFF...............###FFFFFFFFFFFFFF#####...............................F.FFF..FF^^^^FFF....', // 43
  '........................................D^D############................####FFFFFFFFFFF######..............................FFFFFFFFFFFF..........', // 44
  '........................................D^D###########..................####################............................###################.....', // 45
  '.........................................^D##########...................###################..##.......................##DDDDDDDDDDDDDDDDD^##....', // 46
  '.........................................^D##########...................##DDDDDDDDDDD######..###......................##DDDDDDDDDDDDDDDDD^^#....', // 47
  '.........................................^D#########.....................#DDDDDDDDDDD#####...###......................##DDDDDDDDDDDDDDDDDD^##...', // 48
  '.........................................^D#########.....................#DDDDDDDDDDD#^###....##.......................#DDDDDDDDDDDDDDDDDD^##...', // 49
  '.........................................D^#########......................DDDDDDDDDDD#^##..............................#DDDDDDDDDDDDDDDDDD^##...', // 50
  '.........................................#^########.......................DDDDDDDDDDD#^#.................................DDDDDDDDDDDDDDDDD##....', // 51
  '.........................................#^########........................DDDDDDDDDD##...................................#################.....', // 52
  '.........................................#^DDDDD##............................########........................................................##', // 53
  '..........................................^DDDDD##............................................................................................^.', // 54
  '..........................................^DDDDD#..................................................................................##..........#', // 55
  '..........................................#^DDDD..............................................................................................#.', // 56
  '..........................................#^DDD.................................................................................................', // 57
  '..........................................#DDD..................................................................................................', // 58
  '...........................................##...................................................................................................', // 59
  '................................................................................................................................................', // 60
  '................................................................................................................................................', // 61
  'P...P...P........P...P...P........P...P...P........P...P...P........P...P...P........P...P...P........P...P...P........P...P...P........P...P...', // 62
  'P.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP.P.PP.PP.PP', // 63
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 64
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 65
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 66
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 67
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 68
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 69
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 70
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 71
];